FROM python:3.11-slim
WORKDIR /app

# pip 최신화
RUN pip install --upgrade pip

# FastAPI 서버 관련
RUN pip install fastapi uvicorn[standard] redis pydantic

# Hugging Face 및 모델 관련
RUN pip install transformers accelerate bitsandbytes

# PyTorch (CUDA 12.6 GPU 버전)
RUN pip install torch==2.11.0+cu126 --extra-index-url https://download.pytorch.org/whl/cu126

COPY . .

CMD ["python", "modelServer.py"]